version: "3.8"
services:
  liff:
    image: iarc/iaec-webhook:latest
    container_name: mysystem-webhook
    environment:
      - NODE_ENV=production
      - SECRET=your_shared_secret
      - WEBHOOK_TOKEN=your_shared_webhook_token
      - PASSWORD=your_password
    # If you run in portainer remove the ports
    ports:
      # Host:Container
      - "3004:3004"
    # If you run in portainer or use nginx-proxy ui add the network
    # If you use nginx on host machine (command line) remove the networks
    networks:
      - nginx-proxy_default

# If you use nginx on host machine (command line) remove the networks
networks:
  nginx-proxy_default:
    external: true
